name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # clender
          base: header, isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Ahmed Agamy, AhmedEhabAgamy, AhmedEhabAgamy@users.noreply.github.com

          # title color
          config_color_titles: 8A2BE2

  icons:
    name: Icons
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

