name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # runs daily
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Basic metrics
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Cairo

          # ✅ Enable isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
